#ifndef SYSTEMSOFTWARE2_CONSTANTS_H
#define SYSTEMSOFTWARE2_CONSTANTS_H

#define PORT 3874
#define IP "127.0.0.1"
#define LENGTH 512
#define OK_MESSAGE "OK"
#define ID_SIZE 30

#endif //SYSTEMSOFTWARE2_CONSTANTS_H
